# name: test-code
# on: [push]

# jobs:
#   test-code:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' 
#       - name: Install Packages
#         run: |
#           pip install poetry && \
#           poetry export \
#             -f requirements.txt \
#             --output requirements.txt \
#             --without-hashes && \
#           pip install -r requirements.txt
#         shell: bash
#       - name: Run Pytest
#         run: pytest -vv .
#         shell: bash